language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y

install:
  - composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
