language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - sudo apt-get install gcc-multilib
  - sudo apt-get install gdb

install:
  - export LD_LIBRARY_PATH=`pwd`/temp
  - composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
